### ISSUE TITLE
Gewichten per positie

### ISSUE THREAD

**Issue by YellinD** [FusionDota2/KayzrTeamSort#1]
Aangezien high mmr spelers meer impact hebben op core roles, zou ik voorstellen om per positie een bepaald gewicht aan de mmr te hangen. Voor het toernooi van 5/1 heb ik het eens nagerekend, en gebaseerd op de avg mmr met de gewichten per positie, was er maar 1 upset in alle gespeelde wedstrijden en alle andere uitslagen lagen in de lijn van de verwachtingen.

Gedachtengang hierachter is dat een 6k speler op poisitie 1 of 2 veel meer impact op de game kan hebben dan een 6k speler op positie 4 of 5. Po pos 4 en 5 heb je te weinig slagkracht om de game te carry'en. (hoe lager avg mmr, hoe meer impact een high mmr speler op core positie heeft)

De gewichten die toen gebruikt zijn:
pos 1: 1.8
pos 2: 1.8
pos 3: 1.5
pos 4: 1
pos 5: 1

**Comment by FusionDota2** [comment]
New version is pushed. Weighted.
